In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Load the data

In [2]:
data = pd.read_csv(r"C:\Users\athir\Data sets\ML\Wholesale customers data.csv")
data.head()

Channel  Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen
0        2       3  12669  9656     7561     214              2674        1338
1        2       3   7057  9810     9568    1762              3293        1776
2        2       3   6353  8808     7684    2405              3516        7844
3        1       3  13265  1196     4221    6404               507        1788
4        2       3  22615  5410     7198    3915              1777        5185

In [3]:
data.shape

(440, 8)

# Data cleaning, data wrangling

In [4]:
data = data.drop('Channel',axis = 1)
data.head()

Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen
0       3  12669  9656     7561     214              2674        1338
1       3   7057  9810     9568    1762              3293        1776
2       3   6353  8808     7684    2405              3516        7844
3       3  13265  1196     4221    6404               507        1788
4       3  22615  5410     7198    3915              1777        5185

# selecting any 3 columns from the data to perform K means clustering

In [5]:
x = data[['Fresh', 'Milk', 'Grocery']]
x

Fresh   Milk  Grocery
0    12669   9656     7561
1     7057   9810     9568
2     6353   8808     7684
3    13265   1196     4221
4    22615   5410     7198
..     ...    ...      ...
435  29703  12051    16027
436  39228   1431      764
437  14531  15488    30243
438  10290   1981     2232
439   2787   1698     2510

[440 rows x 3 columns]

# Create numpy array of the data

In [6]:
x = x.iloc[: , : ].values
x

array([[12669,  9656,  7561],
       [ 7057,  9810,  9568],
       [ 6353,  8808,  7684],
       ...,
       [14531, 15488, 30243],
       [10290,  1981,  2232],
       [ 2787,  1698,  2510]], dtype=int64)

# Applying K means clustering

In [7]:
from sklearn.cluster import KMeans
kmeans = KMeans()
kmeans

KMeans()

In [8]:
kmeans.fit(x)

KMeans()

# Checking centre values of the cluster

In [9]:
kmeans.cluster_centers_

array([[  7013.71875   ,  17636.3125    ,  27308.46875   ],
       [ 14499.00970874,   2657.60194175,   3486.63106796],
       [ 47092.47619048,   3248.38095238,   4609.66666667],
       [ 31259.4       ,  51254.6       ,  52046.6       ],
       [ 25664.52941176,   5344.68627451,   7054.09803922],
       [  4451.32624113,   2559.17730496,   3118.93617021],
       [112151.        ,  29627.        ,  18148.        ],
       [  4283.44186047,   8427.01162791,  12684.36046512]])

# Applying K means clustering with a different K value

In [10]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters = 5)
kmeans

KMeans(n_clusters=5)

In [11]:
kmeans.fit(x)

KMeans(n_clusters=5)

In [12]:
kmeans.cluster_centers_

array([[20929.87387387,  3943.79279279,  5224.90990991],
       [ 5697.26470588,  3742.69747899,  4736.57983193],
       [30445.        , 48782.66666667, 47042.        ],
       [50049.68181818,  4447.40909091,  5225.04545455],
       [ 5034.96825397, 13195.15873016, 22128.38095238]])